sudo: false
language: node_js
cache:
  directories:
    - node_modules
branches:
  only:
    - master
    - /^greenkeeper/.*$/
notifications:
  email: false
node_js:
  - '5'
  - '6'
after_success: npm run coverage
